(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const CORE='entrenador-v03', PROFILE='entrenador-v032-profile', DAILY='entrenador-v032-daily', PLANS='entrenador-v04-plans', CLINICAL='entrenador-v04-clinical';
const WORKOUTS='entrenador-v05-workouts', GOALS='entrenador-v05-goals';
const COACH='https://entrenador-personal-coach.morrondin.workers.dev';
const iso=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=msg=>{const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hide');setTimeout(()=>t.classList.add('hide'),2400)};

const css=document.createElement('style');
css.textContent=`
body{padding-bottom:calc(112px + env(safe-area-inset-bottom))!important}.tabs{position:fixed!important;left:0!important;right:0!important;top:auto!important;bottom:0!important;transform:none!important;z-index:100!important;min-height:76px;background:#081612fa!important}.app{padding-bottom:24px!important}
.v05-modal{position:fixed;inset:0;z-index:220;background:#020806f5;overflow:auto;padding:max(54px,env(safe-area-inset-top)) 12px calc(110px + env(safe-area-inset-bottom))}.v05-box{max-width:620px;margin:auto}.v05-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.v05-close{width:42px;height:42px;border:1px solid var(--l);background:#081813;color:var(--t);border-radius:12px;font-size:22px}.v05-ex{background:#0a1b15;border:1px solid var(--l);border-radius:16px;padding:13px;margin:10px 0}.v05-ex h3{margin:0 0 5px;font-size:16px}.v05-set{display:grid;grid-template-columns:38px 1fr 1fr 52px;gap:7px;align-items:center;margin:8px 0}.v05-set input{padding:10px}.v05-check{width:48px;height:42px;border:1px solid var(--l);border-radius:10px;background:#081813;color:var(--m);font-weight:900}.v05-check.on{background:var(--g);color:#07120f}.v05-last{font-size:11px;color:var(--g);margin:5px 0}.v05-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v05-chatlog{max-height:48vh;overflow:auto;margin:10px 0}.v05-msg{padding:10px 12px;border-radius:13px;margin:7px 0;line-height:1.4;font-size:13px}.v05-me{background:#204538;margin-left:32px}.v05-coach{background:#081813;border:1px solid var(--l);margin-right:20px}.v05-editlist .item{position:relative;padding-right:82px}.v05-editbuttons{position:absolute;right:0;top:9px;display:flex;gap:5px}.v05-mini{border:1px solid var(--l);background:#081813;color:var(--g);border-radius:9px;padding:7px 8px;font-size:11px}.v05-goal{background:#081813;border:1px solid var(--l);border-radius:14px;padding:12px;margin:8px 0}.v05-goalhead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.v05-garmin{margin:10px 0}.v05-sectionnote{font-size:12px;color:var(--m);line-height:1.45}.coach-card .v05-chatbtn{margin-top:8px}.v05-done{opacity:.62}.v05-setlabels{display:grid;grid-template-columns:38px 1fr 1fr 52px;gap:7px;font-size:10px;color:var(--m);margin-top:10px}.v05-rehab{border-color:#6c8e59;background:#102016}
@media(max-width:390px){.v05-set{grid-template-columns:34px 1fr 1fr 46px}.v05-actions{grid-template-columns:1fr}}
`;
document.head.appendChild(css);

// Persistencia de recursos, incluida bici estática.
function restoreResources(){
 const profile=read(PROFILE,{});const resources=profile.resources||[];const box=$('#resources');if(!box)return;
 if(!box.querySelector('[data-resource="Bici estática"]'))box.insertAdjacentHTML('beforeend','<button type="button" class="chip" data-resource="Bici estática">Bici estática</button>');
 $$('[data-resource]').forEach(b=>{b.classList.toggle('on',resources.includes(b.dataset.resource));if(!b.dataset.v05){b.dataset.v05='1';b.addEventListener('click',()=>setTimeout(()=>{const p=read(PROFILE,{});p.resources=$$('[data-resource].on').map(x=>x.dataset.resource);write(PROFILE,p)},0))}});
}
restoreResources();setTimeout(restoreResources,400);

// Objetivos editables.
function defaultGoals(){const p=read(PROFILE,{}),g=p.goals||{};return [
 {id:'body',title:'💪 Físico y fuerza',detail:g.body||'Mejorar físico y fuerza',date:g.bodyDate||'2026-12-31',status:'activo'},
 {id:'achilles',title:'🦶 Recuperar el Aquiles',detail:g.achilles||'Recuperar Aquiles sin recaídas',date:'',status:'activo'},
 {id:'smoke',title:'🚭 Dejar de fumar',detail:'Mantener seguimiento de recaídas y racha',date:p.quitDate||'2026-09-08',status:'activo'},
 {id:'race',title:'🏃 Objetivo deportivo',detail:g.race||'San Silvestre 2027',date:g.raceDate||'2027-12-31',status:'activo'}
]}
let goals=read(GOALS,null)||defaultGoals();write(GOALS,goals);
function goalRow(){return [...$$('#v-datos .row')].find(r=>r.querySelector('.label')?.textContent.trim()==='Objetivos')}
function renderGoals(){const row=goalRow();if(!row)return;row.innerHTML=`<span class="label">Objetivos</span><div id="v05Goals"></div><button type="button" class="btn alt" id="addGoal">＋ AÑADIR OBJETIVO</button>`;const box=$('#v05Goals');box.innerHTML=goals.map(g=>`<div class="v05-goal"><div class="v05-goalhead"><div><strong>${safe(g.title)}</strong><div class="v32note">${safe(g.detail)}</div>${g.date?`<span class="badge">${safe(g.date)}</span>`:''}</div><div><button class="v05-mini" data-ge="${g.id}">Editar</button> <button class="v05-mini" data-gd="${g.id}">×</button></div></div></div>`).join('');
 $$('[data-ge]').forEach(b=>b.onclick=()=>openGoal(b.dataset.ge));$$('[data-gd]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este objetivo?')){goals=goals.filter(g=>g.id!==b.dataset.gd);write(GOALS,goals);renderGoals()}});$('#addGoal').onclick=()=>openGoal('');}
function openGoal(id){const g=goals.find(x=>x.id===id)||{id:'g'+Date.now(),title:'',detail:'',date:'',status:'activo'};openModal(`<div class="v05-head"><h2>${id?'Editar':'Nuevo'} objetivo</h2><button class="v05-close" data-close>×</button></div><form class="card" id="goalForm"><label class="label">Nombre</label><input id="gt" value="${safe(g.title)}"><label class="label" style="margin-top:10px">Descripción</label><textarea id="gd">${safe(g.detail)}</textarea><label class="label">Fecha objetivo (opcional)</label><input id="gdate" type="date" value="${safe(g.date)}"><button class="btn" style="margin-top:12px">GUARDAR OBJETIVO</button></form>`);$('#goalForm').onsubmit=e=>{e.preventDefault();const n={...g,title:$('#gt').value.trim(),detail:$('#gd').value.trim(),date:$('#gdate').value};goals=goals.filter(x=>x.id!==n.id);goals.push(n);write(GOALS,goals);closeModal();renderGoals();notify('Objetivo guardado')}}
setTimeout(renderGoals,300);

// Modal genérico v0.5.
let modal=null;
function openModal(html){closeModal();modal=document.createElement('div');modal.className='v05-modal';modal.innerHTML=`<div class="v05-box">${html}</div>`;document.body.appendChild(modal);document.body.style.overflow='hidden';modal.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}
function closeModal(){if(modal){modal.remove();modal=null}document.body.style.overflow=''}

// Historial de actividades editable.
function activityEditCard(){let card=$('#v05ActivityEdit');if(card)return card;const view=$('#v-historial');if(!view)return null;card=document.createElement('div');card.id='v05ActivityEdit';card.className='card';card.innerHTML='<h2>Editar actividades</h2><p class="sub">Corrige o elimina registros guardados.</p><div id="v05ActivityList" class="v05-editlist"></div>';view.prepend(card);return card}
function renderEditableActivities(){activityEditCard();const core=read(CORE,{activities:[]});const list=$('#v05ActivityList');if(!list)return;list.innerHTML=(core.activities||[]).slice().reverse().map(a=>`<div class="item"><h3>${safe(a.type||'Actividad')}</h3><p>${safe(a.date||'')} · ${a.duration||'—'} min · ${a.distance||'—'} km ${a.exerciseLog?'· '+a.exerciseLog.length+' ejercicios':''}</p><div class="v05-editbuttons"><button class="v05-mini" data-ae="${safe(a.id)}">Editar</button><button class="v05-mini" data-ad="${safe(a.id)}">×</button></div></div>`).join('')||'<div class="empty">Sin actividades todavía.</div>';
 $$('[data-ae]').forEach(b=>b.onclick=()=>editActivity(b.dataset.ae));$$('[data-ad]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar esta actividad?')){const c=read(CORE,{checkins:{},activities:[]});c.activities=(c.activities||[]).filter(a=>String(a.id)!==String(b.dataset.ad));write(CORE,c);renderEditableActivities();notify('Actividad eliminada')}})}
function editActivity(id){const core=read(CORE,{checkins:{},activities:[]});const a=(core.activities||[]).find(x=>String(x.id)===String(id));if(!a)return;openModal(`<div class="v05-head"><h2>Editar actividad</h2><button class="v05-close" data-close>×</button></div><form class="card" id="editActivityForm"><div class="grid"><div><label class="label">Tipo</label><input id="eat" value="${safe(a.type||'')}"></div><div><label class="label">Fecha</label><input id="ead" type="date" value="${safe(a.date||iso())}"></div><div><label class="label">Duración min</label><input id="eamin" type="number" value="${safe(a.duration||'')}"></div><div><label class="label">Distancia km</label><input id="eakm" type="number" step=".01" value="${safe(a.distance||'')}"></div><div><label class="label">FC media</label><input id="eahr" type="number" value="${safe(a.avgHr||'')}"></div><div><label class="label">RPE</label><input id="earpe" type="number" min="1" max="10" value="${safe(a.rpe||'')}"></div></div><label class="label" style="margin-top:10px">Notas</label><textarea id="ean">${safe(a.notes||'')}</textarea><button class="btn" style="margin-top:12px">GUARDAR CAMBIOS</button></form>`);$('#editActivityForm').onsubmit=e=>{e.preventDefault();Object.assign(a,{type:$('#eat').value,date:$('#ead').value,duration:$('#eamin').value,distance:$('#eakm').value,avgHr:$('#eahr').value,rpe:$('#earpe').value,notes:$('#ean').value});write(CORE,core);closeModal();renderEditableActivities();notify('Actividad actualizada')}}
$$('.tab').forEach(t=>t.addEventListener('click',()=>{if(t.dataset.tab==='historial')setTimeout(renderEditableActivities,50);if(t.dataset.tab==='datos')setTimeout(()=>{restoreResources();renderGoals()},50)}));

// Datos de sesión interactiva.
function getPlan(){return read(PLANS,{})[iso()]||null}
function workoutStore(){return read(WORKOUTS,{})}
function lastExercise(name){const ws=Object.values(workoutStore()).filter(w=>w.completedAt).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));for(const w of ws){const e=(w.exercises||[]).find(x=>x.name.toLowerCase()===String(name).toLowerCase());if(e)return e}return null}
function targetReps(text){const m=String(text||'').match(/(\d+)/);return m?m[1]:''}
function createWorkoutFromPlan(plan){const old=workoutStore()[iso()];if(old&&old.planGeneratedAt===plan.generatedAt)return old;const ex=(plan.session?.exercises||[]).map((x,i)=>{const last=lastExercise(x.name);const n=Math.max(1,Number(x.sets)||1);return {id:'e'+i,name:x.name,planned:x,sets:Array.from({length:n},(_,j)=>({set:j+1,weight:last?.sets?.[j]?.weight||'',reps:targetReps(x.reps),done:false})),done:false}});return {date:iso(),planGeneratedAt:plan.generatedAt||'',title:plan.session?.title||'Sesión',startedAt:new Date().toISOString(),exercises:ex}}
function saveWorkout(w){const all=workoutStore();all[iso()]=w;write(WORKOUTS,all)}
function openWorkout(){const plan=getPlan();if(!plan?.session)return notify('No hay una sesión preparada');const w=createWorkoutFromPlan(plan);saveWorkout(w);renderWorkout(w)}
function renderWorkout(w){openModal(`<div class="v05-head"><div><span class="tag">MODO ENTRENAMIENTO</span><h2>${safe(w.title)}</h2></div><button class="v05-close" data-close>×</button></div><div class="v05-actions"><button class="btn alt" id="chatCoach">💬 PREGUNTAR AL ENTRENADOR</button><button class="btn alt" id="saveAndExit">GUARDAR Y SALIR</button></div><div id="v05Exercises"></div><button class="btn" id="finishWorkout">✅ FINALIZAR ENTRENAMIENTO</button>`);const box=$('#v05Exercises');box.innerHTML=w.exercises.map((e,i)=>{const last=lastExercise(e.name);const rehab=/aquiles|tobillo|gemelo|sóleo|soleo|banda|movilidad/i.test(e.name);return `<div class="v05-ex ${rehab?'v05-rehab':''} ${e.done?'v05-done':''}" data-ex="${i}"><h3>${i+1}. ${safe(e.name)}</h3>${last?`<div class="v05-last">Última vez: ${last.sets.map(s=>`${s.weight||'—'} kg × ${s.reps||'—'}`).join(' · ')}</div>`:''}<p class="v05-sectionnote"><strong>Plan:</strong> ${safe(e.planned.sets)} series · ${safe(e.planned.reps)} · descanso ${safe(e.planned.rest_seconds)} s<br>${safe(e.planned.load_guidance)}<br>${safe(e.planned.technique)}</p><div class="v05-setlabels"><span>Serie</span><span>Peso kg</span><span>Reps</span><span>Hecho</span></div>${e.sets.map((s,j)=>`<div class="v05-set"><b>${j+1}</b><input type="number" step=".5" inputmode="decimal" data-w="${i}" data-s="${j}" data-k="weight" value="${safe(s.weight)}"><input type="number" inputmode="numeric" data-w="${i}" data-s="${j}" data-k="reps" value="${safe(s.reps)}"><button class="v05-check ${s.done?'on':''}" data-check="${i}:${j}">${s.done?'✓':'○'}</button></div>`).join('')}<button class="btn alt" data-exdone="${i}">${e.done?'✓ EJERCICIO HECHO':'MARCAR EJERCICIO HECHO'}</button></div>`}).join('');
 $$('[data-w]').forEach(inp=>inp.onchange=()=>{const i=+inp.dataset.w,j=+inp.dataset.s,k=inp.dataset.k;w.exercises[i].sets[j][k]=inp.value;saveWorkout(w)});$$('[data-check]').forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.check.split(':').map(Number);w.exercises[i].sets[j].done=!w.exercises[i].sets[j].done;w.exercises[i].done=w.exercises[i].sets.every(s=>s.done);saveWorkout(w);renderWorkout(w)});$$('[data-exdone]').forEach(b=>b.onclick=()=>{const e=w.exercises[+b.dataset.exdone];e.done=!e.done;e.sets.forEach(s=>s.done=e.done);saveWorkout(w);renderWorkout(w)});$('#saveAndExit').onclick=()=>{saveWorkout(w);closeModal();notify('Progreso guardado')};$('#chatCoach').onclick=()=>openChat(w);$('#finishWorkout').onclick=()=>finishWorkout(w)}
function finishWorkout(w){w.completedAt=new Date().toISOString();saveWorkout(w);const core=read(CORE,{checkins:{},activities:[]});const existing=(core.activities||[]).find(a=>a.workoutDate===iso());const log=w.exercises.map(e=>({name:e.name,sets:e.sets,done:e.done}));const activity={id:existing?.id||('workout-'+Date.now()),date:iso(),workoutDate:iso(),type:'Fuerza / sesión guiada',duration:'',distance:'',avgHr:'',maxHr:'',elevation:'',calories:'',rpe:'',postAchilles:'',notes:`Sesión guiada: ${w.title}`,exerciseLog:log,savedAt:new Date().toISOString()};core.activities=(core.activities||[]).filter(a=>a.id!==existing?.id);core.activities.push(activity);write(CORE,core);closeModal();renderEditableActivities();notify('Entrenamiento completado y guardado')}

// Inyectar botones sobre el plan generado.
function enhancePlan(){const p=$('#coachPlan');if(!p||p.classList.contains('hide'))return;if(!p.querySelector('.v05-chatbtn')){const actions=document.createElement('div');actions.className='v05-actions v05-chatbtn';actions.innerHTML='<button class="btn alt" id="v05ChatBefore">💬 PREGUNTAR / CAMBIAR</button><button class="btn" id="v05StartWorkout">▶ EMPEZAR ENTRENAMIENTO</button>';p.appendChild(actions);$('#v05ChatBefore').onclick=()=>openChat(workoutStore()[iso()]||null);$('#v05StartWorkout').onclick=openWorkout}const old=$('#beginCoach');if(old)old.style.display='none'}
const obs=new MutationObserver(()=>enhancePlan());const coachPlan=$('#coachPlan');if(coachPlan)obs.observe(coachPlan,{childList:true,subtree:true,attributes:true});setTimeout(enhancePlan,500);

// Chat contextual con el entrenador.
let chatHistory=[];
function contextPayload(w){const profile=read(PROFILE,{}),core=read(CORE,{checkins:{},activities:[]}),daily=read(DAILY,{}),clinical=read(CLINICAL,{}),plan=getPlan();return {message:'',profile:{...profile,goals},checkin:core.checkins?.[iso()]||{},daily:daily[iso()]||{},currentPlan:plan,workoutProgress:w||workoutStore()[iso()]||null,recentHistory:(core.activities||[]).slice(-12),confirmedRestrictions:clinical.confirmedRestrictions||[]}}
function openChat(w){openModal(`<div class="v05-head"><div><span class="tag">ENTRENADOR</span><h2>Pregunta o cambia algo</h2></div><button class="v05-close" data-close>×</button></div><div class="card"><p class="v05-sectionnote">Puedes escribir: “¿Puedo meter pierna?”, “esta máquina está ocupada”, “me molesta más el Aquiles” o “quiero cambiar este ejercicio”.</p><div id="chatLog" class="v05-chatlog"></div><textarea id="chatText" placeholder="Escribe tu pregunta…"></textarea><button class="btn" id="sendChat" style="margin-top:8px">ENVIAR</button></div>`);renderChat();$('#sendChat').onclick=async()=>{const text=$('#chatText').value.trim();if(!text)return;chatHistory.push({role:'me',text});renderChat();$('#chatText').value='';const payload=contextPayload(w);payload.message=text;payload.chatHistory=chatHistory.slice(-8);$('#sendChat').disabled=true;try{const r=await fetch(COACH+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||'Error');chatHistory.push({role:'coach',text:d.reply||'Sin respuesta'});if(d.updated_session){const plans=read(PLANS,{});const p=plans[iso()]||{};p.session=d.updated_session;p.generatedAt=new Date().toISOString();plans[iso()]=p;write(PLANS,plans);chatHistory.push({role:'coach',text:'He actualizado la sesión. Cierra el chat y verás el nuevo plan.'});const all=workoutStore();delete all[iso()];write(WORKOUTS,all)}renderChat()}catch(e){chatHistory.push({role:'coach',text:'No pude responder: '+e.message});renderChat()}finally{$('#sendChat').disabled=false}}}
function renderChat(){const l=$('#chatLog');if(!l)return;l.innerHTML=chatHistory.map(m=>`<div class="v05-msg ${m.role==='me'?'v05-me':'v05-coach'}">${safe(m.text)}</div>`).join('');l.scrollTop=l.scrollHeight}

// Garmin: lectura automática de captura.
function addGarminReader(){const form=$('#activity');if(!form||$('#v05ReadGarmin'))return;const b=document.createElement('button');b.type='button';b.id='v05ReadGarmin';b.className='btn alt v05-garmin';b.textContent='✨ LEER CAPTURA AUTOMÁTICAMENTE';const preview=$('#preview');preview?.after(b);b.onclick=async()=>{const f=$('#image')?.files?.[0];if(!f)return notify('Selecciona primero una captura Garmin');if(f.size>1800000)return notify('Recorta la captura: máximo 1,8 MB');b.disabled=true;b.textContent='Leyendo captura…';try{const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const r=await fetch(COACH+'/garmin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:dataUrl})});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||'Error');const typeMap={'Fuerza':'Fuerza','Carrera':'Carrera','Bici':'Bici','Caminar':'Caminar','Movilidad':'Movilidad','Otro':'Otro'};if(d.type&&typeMap[d.type])$('#type').value=typeMap[d.type];if(d.date)$('#activityDate').value=d.date;if(d.duration_minutes!=null)$('#duration').value=d.duration_minutes;if(d.distance_km!=null)$('#distance').value=d.distance_km;if(d.avg_hr!=null)$('#avgHr').value=d.avg_hr;if(d.max_hr!=null)$('#maxHr').value=d.max_hr;if(d.elevation_m!=null)$('#elevation').value=d.elevation_m;if(d.calories!=null)$('#calories').value=d.calories;if(d.notes)$('#notes').value=d.notes;notify('Datos Garmin leídos: revisa y guarda')}catch(e){notify('No pude leer la captura: '+e.message)}finally{b.disabled=false;b.textContent='✨ LEER CAPTURA AUTOMÁTICAMENTE'}}}
$('#garmin')?.addEventListener('click',()=>setTimeout(addGarminReader,60));$('#start')?.addEventListener('click',()=>setTimeout(addGarminReader,60));

// Añadir metas al payload del coach y mantener opciones múltiples ya definidas por v0.4.3.
const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input?.url||'';if(url.endsWith('/coach')&&init?.body){try{const body=JSON.parse(init.body);body.profile=body.profile||{};body.profile.goals=goals;init={...init,body:JSON.stringify(body)}}catch{}}return nativeFetch(input,init)};

// Versión visible.
const ver=()=>{const d=$('#date');if(d)d.innerHTML=d.innerHTML.replace(/v0\.4(?:\.2|\.3)?/,'v0.5');const v=$('.version');if(v)v.textContent='Entrenador Personal · v0.5'};ver();setTimeout(ver,500);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=050').then(r=>r.update()).catch(()=>{}));
})();