(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WORKOUTS='entrenador-v05-workouts',CORE='entrenador-v03';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.remove('hide');setTimeout(()=>t.classList.add('hide'),2200)};
function modal(html){const m=document.createElement('div');m.className='v05-modal';m.innerHTML=`<div class="v05-box">${html}</div>`;document.body.appendChild(m);document.body.style.overflow='hidden';const close=()=>{m.remove();document.body.style.overflow=''};m.querySelectorAll('[data-v051-close]').forEach(b=>b.onclick=close);return {m,close}}
function renderSessions(){const view=$('#v-historial');if(!view)return;let card=$('#v051Sessions');if(!card){card=document.createElement('div');card.id='v051Sessions';card.className='card';const anchor=$('#v05ActivityEdit');anchor?anchor.after(card):view.prepend(card)}const all=read(WORKOUTS,{});const list=Object.values(all).filter(w=>w.completedAt).sort((a,b)=>String(b.date).localeCompare(String(a.date)));card.innerHTML=`<h2>Sesiones guiadas</h2><p class="sub">Edita pesos, repeticiones y series después del entrenamiento.</p>${list.length?list.map(w=>`<div class="item"><div class="itemtop"><h3>${safe(w.title||'Entrenamiento')}</h3><span class="muted">${safe(w.date)}</span></div><p>${(w.exercises||[]).length} ejercicios</p><button class="btn alt" data-wedit="${safe(w.date)}">EDITAR SERIES</button></div>`).join(''):'<div class="empty">Aún no hay sesiones finalizadas.</div>'}`;$$('[data-wedit]').forEach(b=>b.onclick=()=>editWorkout(b.dataset.wedit))}
function editWorkout(date){const all=read(WORKOUTS,{}),w=all[date];if(!w)return;const {m,close}=modal(`<div class="v05-head"><div><span class="tag">EDITAR SESIÓN</span><h2>${safe(w.title)}</h2></div><button class="v05-close" data-v051-close>×</button></div><div class="card" id="v051EditBody"></div><button class="btn" id="v051Save">GUARDAR CAMBIOS</button>`);const body=m.querySelector('#v051EditBody');body.innerHTML=(w.exercises||[]).map((e,i)=>`<div class="v05-ex"><h3>${i+1}. ${safe(e.name)}</h3><div class="v05-setlabels"><span>Serie</span><span>Peso kg</span><span>Reps</span><span>Hecho</span></div>${(e.sets||[]).map((s,j)=>`<div class="v05-set"><b>${j+1}</b><input type="number" step=".5" data-e="${i}" data-s="${j}" data-k="weight" value="${safe(s.weight)}"><input type="number" data-e="${i}" data-s="${j}" data-k="reps" value="${safe(s.reps)}"><button class="v05-check ${s.done?'on':''}" data-d="${i}:${j}">${s.done?'✓':'○'}</button></div>`).join('')}</div>`).join('');
 m.querySelectorAll('[data-k]').forEach(inp=>inp.onchange=()=>{w.exercises[+inp.dataset.e].sets[+inp.dataset.s][inp.dataset.k]=inp.value});m.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.d.split(':').map(Number);const s=w.exercises[i].sets[j];s.done=!s.done;b.classList.toggle('on',s.done);b.textContent=s.done?'✓':'○';w.exercises[i].done=w.exercises[i].sets.every(x=>x.done)});m.querySelector('#v051Save').onclick=()=>{all[date]=w;write(WORKOUTS,all);const core=read(CORE,{checkins:{},activities:[]});const a=(core.activities||[]).find(x=>x.workoutDate===date);if(a)a.exerciseLog=w.exercises.map(e=>({name:e.name,sets:e.sets,done:e.done}));write(CORE,core);close();renderSessions();notify('Series actualizadas')}}
$$('.tab').forEach(t=>t.addEventListener('click',()=>{if(t.dataset.tab==='historial')setTimeout(renderSessions,80)}));setTimeout(renderSessions,700);

// Si el chat devuelve una sesión modificada, recarga el plan una vez guardado para verla inmediatamente.
const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input?.url||'';const res=await nativeFetch(input,init);if(url.endsWith('/chat')&&res.ok){try{const d=await res.clone().json();if(d.updated_session)setTimeout(()=>{if(document.querySelector('.v05-modal')){notify('Plan actualizado');setTimeout(()=>location.reload(),900)}},150)}catch{}}return res};
})();