(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WORKOUTS='entrenador-v05-workouts',CORE='entrenador-v03';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.remove('hide');setTimeout(()=>t.classList.add('hide'),2200)};
const summary=w=>{const total=(w.exercises||[]).length,done=(w.exercises||[]).filter(e=>e.done||(e.sets||[]).length&&(e.sets||[]).every(s=>s.done)).length;return `${w.duration||0} min · ${done}/${total} ejercicios realizados`};
function closeModal(m){m.remove();document.body.style.overflow=''}
function activityFor(core,date){return (core.activities||[]).find(a=>a.workoutDate===date)}
function syncActivity(w,a){return {...(a||{}),id:a?.id||('manual-session-'+w.date),date:w.date,workoutDate:w.date,type:'Entrenamiento',duration:String(w.duration||''),notes:`${w.title}. ${summary(w)}.`,exerciseLog:(w.exercises||[]).map(e=>({name:e.name,sets:e.sets,done:e.done})),savedAt:new Date().toISOString(),source:w.source||'manual'}}
function editSession(key){
 const all=read(WORKOUTS,{}),w=all[key];if(!w)return;
 const m=document.createElement('div');m.className='v05-modal';m.innerHTML=`<div class="v05-box"><div class="v05-head"><div><span class="tag">EDITAR ENTRENAMIENTO</span><h2>${safe(w.title)}</h2></div><button class="v05-close" data-close>×</button></div><form id="v054Form"><div class="card"><div class="grid"><div><label class="label">Nombre</label><input id="v054Title" value="${safe(w.title)}" required></div><div><label class="label">Fecha</label><input id="v054Date" type="date" value="${safe(w.date)}" required></div></div><label class="label" style="margin-top:10px">Duración total (min)</label><input id="v054Duration" type="number" min="0" value="${safe(w.duration||'')}"></div><div id="v054Exercises"></div><button class="btn">GUARDAR ENTRENAMIENTO</button></form></div>`;document.body.appendChild(m);document.body.style.overflow='hidden';m.querySelector('[data-close]').onclick=()=>closeModal(m);
 const box=m.querySelector('#v054Exercises');box.innerHTML=(w.exercises||[]).map((e,i)=>`<div class="card v054-ex"><div class="v054-exhead"><h3>${i+1}. ${safe(e.name)}</h3><label><input type="checkbox" data-exdone="${i}" ${e.done?'checked':''}> Hecho</label></div>${(e.sets||[]).map((s,j)=>`<div class="v05-set"><b>${j+1}</b><input aria-label="Peso kg" type="number" step=".5" inputmode="decimal" data-e="${i}" data-s="${j}" data-k="weight" value="${safe(s.weight)}"><input aria-label="Repeticiones" type="number" inputmode="numeric" data-e="${i}" data-s="${j}" data-k="reps" value="${safe(s.reps)}"><button type="button" class="v05-check ${s.done?'on':''}" data-check="${i}:${j}">${s.done?'✓':'○'}</button></div>`).join('')}</div>`).join('');
 m.querySelectorAll('[data-k]').forEach(inp=>inp.onchange=()=>{w.exercises[+inp.dataset.e].sets[+inp.dataset.s][inp.dataset.k]=inp.value});m.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.check.split(':').map(Number),s=w.exercises[i].sets[j];s.done=!s.done;w.exercises[i].done=w.exercises[i].sets.every(x=>x.done);b.classList.toggle('on',s.done);b.textContent=s.done?'✓':'○';m.querySelector(`[data-exdone="${i}"]`).checked=w.exercises[i].done});m.querySelectorAll('[data-exdone]').forEach(c=>c.onchange=()=>{const e=w.exercises[+c.dataset.exdone];e.done=c.checked;e.sets.forEach(s=>s.done=e.done);e.sets.forEach((s,j)=>{const b=m.querySelector(`[data-check="${c.dataset.exdone}:${j}"]`);b.classList.toggle('on',s.done);b.textContent=s.done?'✓':'○'})});
 m.querySelector('#v054Form').onsubmit=e=>{e.preventDefault();const newDate=m.querySelector('#v054Date').value,core=read(CORE,{checkins:{},activities:[]}),a=activityFor(core,key);w.title=m.querySelector('#v054Title').value.trim();w.date=newDate;w.duration=+m.querySelector('#v054Duration').value||0;delete all[key];all[newDate]=w;core.activities=(core.activities||[]).filter(x=>x!==a);core.activities.push(syncActivity(w,a));write(WORKOUTS,all);write(CORE,core);notify('Entrenamiento actualizado');setTimeout(()=>location.reload(),300)};
}
function removeSession(key){if(!confirm('¿Eliminar este entrenamiento completo?'))return;const all=read(WORKOUTS,{}),core=read(CORE,{checkins:{},activities:[]});delete all[key];core.activities=(core.activities||[]).filter(a=>a.workoutDate!==key);write(WORKOUTS,all);write(CORE,core);notify('Entrenamiento eliminado');setTimeout(()=>location.reload(),300)}
function renderHistory(){
 const view=$('#v-historial');if(!view)return;let card=$('#v054History');if(!card){card=document.createElement('div');card.id='v054History';card.className='card';view.prepend(card)}const sessions=Object.entries(read(WORKOUTS,{})).filter(([,w])=>w.completedAt).sort((a,b)=>String(b[1].date).localeCompare(String(a[1].date)));card.innerHTML=`<div class="v054-title"><div><h2>Historial de entrenamientos</h2><p class="sub">Una ficha completa por sesión.</p></div><button class="v05-mini" id="v054Add">＋ Añadir</button></div>${sessions.length?sessions.map(([key,w])=>`<div class="item v054-item"><div><h3>${safe(w.title||'Entrenamiento')}</h3><p>${safe(w.date)} · ${safe(summary(w))}</p></div><div class="v054-actions"><button class="v05-mini" data-edit="${safe(key)}">Editar</button><button class="v05-mini" data-delete="${safe(key)}">×</button></div></div>`).join(''):'<div class="empty">Sin entrenamientos todavía.</div>'}`;card.querySelector('#v054Add').onclick=()=>$('#v052Open')?.click();card.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editSession(b.dataset.edit));card.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeSession(b.dataset.delete));
}
function calendarDetail(date){const w=read(WORKOUTS,{})[date],detail=$('#detail');if(w&&detail)detail.innerHTML=`<div class="item"><h3>🏋️ ${safe(w.title)}</h3><p>${safe(summary(w))}</p></div>`}
const css=document.createElement('style');css.textContent='#v05ActivityEdit,#v051Sessions,#v052Import,#history{display:none!important}.v054-title,.v054-item,.v054-exhead{display:flex;justify-content:space-between;align-items:center;gap:10px}.v054-actions{display:flex;gap:6px}.v054-item>div:first-child{min-width:0}.v054-ex h3{margin:0}.v054-exhead label{color:var(--m);white-space:nowrap}.v054-exhead input{width:auto}@media(max-width:390px){.v054-item{align-items:flex-start}.v054-actions{flex-direction:column}}';document.head.appendChild(css);
const baseHistory=$('#history')?.closest('.card');if(baseHistory)baseHistory.style.display='none';renderHistory();$$('.tab').forEach(t=>t.addEventListener('click',()=>{if(t.dataset.tab==='historial')setTimeout(renderHistory,140)}));$('#calendar')?.addEventListener('click',e=>{const b=e.target.closest('[data-d]');if(b)setTimeout(()=>calendarDetail(b.dataset.d),0)});
const ver=()=>{const d=$('#date');if(d)d.innerHTML=d.innerHTML.split('<br>')[0]+'<br>v0.5.4';const v=$('.version');if(v)v.textContent='Entrenador Personal · v0.5.4'};ver();setTimeout(ver,900);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=054').then(r=>r.update()).catch(()=>{}));
})();
