(() => {
'use strict';
const PLANS='entrenador-v04-plans',WORKOUTS='entrenador-v05-workouts',CORE='entrenador-v03';
const $=s=>document.querySelector(s),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const repsDefault=t=>{const m=String(t||'').match(/(\d+)/);return m?m[1]:''};
function makeWorkout(){const p=read(PLANS,{})[iso()];if(!p?.session)return null;const old=read(WORKOUTS,{})[iso()];if(old&&!old.completedAt)return old;const w={date:iso(),title:p.session.title||'Sesión de hoy',status:'in_progress',startedAt:new Date().toISOString(),planGeneratedAt:p.generatedAt||'',exercises:(p.session.exercises||[]).map((e,i)=>({id:'e'+i,name:e.name,planned:e,done:false,sets:Array.from({length:Math.max(1,Number(e.sets)||1)},(_,j)=>({set:j+1,weight:'',reps:repsDefault(e.reps),done:false}))}))};const all=read(WORKOUTS,{});all[iso()]=w;write(WORKOUTS,all);return w}
function save(w){const all=read(WORKOUTS,{});all[iso()]=w;write(WORKOUTS,all)}
function discard(){const all=read(WORKOUTS,{}),w=all[iso()];if(!w||w.completedAt)return;if(!confirm('¿Descartar el entrenamiento en curso de hoy? Se borrarán las series marcadas, pero se conservará la propuesta.'))return;delete all[iso()];write(WORKOUTS,all);location.reload()}
function finish(w){w.completedAt=new Date().toISOString();w.status='completed';save(w);const core=read(CORE,{checkins:{},activities:[]});core.activities=(core.activities||[]).filter(a=>a.workoutDate!==w.date);core.activities.push({id:'guided-'+w.date,date:w.date,workoutDate:w.date,type:'Entrenamiento',duration:'',distance:'',notes:w.title,exerciseLog:w.exercises.map(e=>({name:e.name,sets:e.sets,done:e.done})),savedAt:w.completedAt,completedAt:w.completedAt,status:'completed',source:'guided'});write(CORE,core);alert('Entrenamiento finalizado y guardado.');location.reload()}
function openWorkout(w){document.querySelectorAll('.v063-modal').forEach(x=>x.remove());const m=document.createElement('div');m.className='v05-modal v063-modal';m.innerHTML=`<div class="v05-box"><div class="v05-head"><div><span class="tag">ENTRENAMIENTO EN CURSO</span><h2>${safe(w.title)}</h2></div><button class="v05-close" data-close>×</button></div><div id="v063Body"></div><button class="btn" id="v063Finish">✅ FINALIZAR ENTRENAMIENTO</button><button class="btn bad" id="v063Discard" style="margin-top:10px">🗑️ DESCARTAR ENTRENAMIENTO</button><button class="btn alt" id="v063Save" style="margin-top:10px">GUARDAR Y SALIR</button></div>`;document.body.appendChild(m);document.body.style.overflow='hidden';const body=m.querySelector('#v063Body');body.innerHTML=w.exercises.map((e,i)=>`<div class="v05-ex"><h3>${i+1}. ${safe(e.name)}</h3><p class="v05-sectionnote">${safe(e.planned?.reps||'')} · descanso ${safe(e.planned?.rest_seconds||'')} s<br>${safe(e.planned?.load_guidance||'')}<br>${safe(e.planned?.technique||'')}</p><div class="v05-setlabels"><span>Serie</span><span>Peso kg</span><span>Reps</span><span>Hecho</span></div>${e.sets.map((s,j)=>`<div class="v05-set"><b>${j+1}</b><input type="number" step=".5" inputmode="decimal" data-i="${i}" data-j="${j}" data-k="weight" value="${safe(s.weight)}"><input type="number" inputmode="numeric" data-i="${i}" data-j="${j}" data-k="reps" value="${safe(s.reps)}"><button type="button" class="v05-check ${s.done?'on':''}" data-check="${i}:${j}">${s.done?'✓':'○'}</button></div>`).join('')}</div>`).join('');m.querySelectorAll('[data-k]').forEach(inp=>inp.onchange=()=>{w.exercises[+inp.dataset.i].sets[+inp.dataset.j][inp.dataset.k]=inp.value;save(w)});m.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.check.split(':').map(Number),s=w.exercises[i].sets[j];s.done=!s.done;w.exercises[i].done=w.exercises[i].sets.every(x=>x.done);b.classList.toggle('on',s.done);b.textContent=s.done?'✓':'○';save(w)});const close=()=>{save(w);m.remove();document.body.style.overflow=''};m.querySelector('[data-close]').onclick=close;m.querySelector('#v063Save').onclick=close;m.querySelector('#v063Discard').onclick=discard;m.querySelector('#v063Finish').onclick=()=>finish(w)}
function begin(e){const b=e.target.closest('#beginCoach');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const w=makeWorkout();if(!w)return alert('No se pudo crear la sesión. Vuelve a generar el entrenamiento.');openWorkout(w)}
document.addEventListener('click',begin,true);
function resumeCard(){const w=read(WORKOUTS,{})[iso()];if(!w||w.completedAt)return;const c=$('#v062InProgress');if(c){const r=c.querySelector('#v062Resume');if(r)r.onclick=()=>openWorkout(read(WORKOUTS,{})[iso()]);const d=c.querySelector('#v062Discard');if(d)d.onclick=discard}}
const obs=new MutationObserver(resumeCard);obs.observe(document.body,{childList:true,subtree:true});resumeCard();
const ver=()=>{const d=$('#date');if(d)d.innerHTML=d.innerHTML.split('<br>')[0]+'<br>v0.6.3';const v=$('.version');if(v)v.textContent='Entrenador Personal · v0.6.3'};ver();setTimeout(ver,900);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=063').then(r=>r.update()).catch(()=>{}));
})();
