(() => {
'use strict';
const PLANS='entrenador-v04-plans',WORKOUTS='entrenador-v05-workouts',CORE='entrenador-v03';
const COACH='https://entrenador-personal-coach.morrondin.workers.dev';
const $=s=>document.querySelector(s),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const repsDefault=t=>{const m=String(t||'').match(/(\d+)/);return m?m[1]:''};
const notify=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.remove('hide');setTimeout(()=>t.classList.add('hide'),2400)};
function store(){return read(WORKOUTS,{})}
function saveWorkout(w){const a=store();a[iso()]=w;write(WORKOUTS,a)}
function lastExercise(name){const ws=Object.values(store()).filter(w=>w?.completedAt).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));for(const w of ws){const e=(w.exercises||[]).find(x=>String(x.name).toLowerCase()===String(name).toLowerCase());if(e)return e}return null}
function makeWorkout(){const p=read(PLANS,{})[iso()];if(!p?.session)return null;const old=store()[iso()];if(old&&!old.completedAt)return old;const w={date:iso(),title:p.session.title||'Sesión de hoy',status:'in_progress',startedAt:new Date().toISOString(),planGeneratedAt:p.generatedAt||'',exercises:(p.session.exercises||[]).map((e,i)=>{const last=lastExercise(e.name),n=Math.max(1,Number(e.sets)||1);return {id:'e'+i,name:e.name,planned:e,done:false,sets:Array.from({length:n},(_,j)=>({set:j+1,weight:last?.sets?.[j]?.weight||'',reps:repsDefault(e.reps),done:false}))}})};saveWorkout(w);return w}
function closeModal(m){m?.remove();document.body.style.overflow=''}
function discard(){const all=store(),w=all[iso()];if(!w||w.completedAt)return;if(!confirm('¿Descartar el entrenamiento en curso de hoy? Se borrarán las series marcadas y se conservará la propuesta.'))return;delete all[iso()];write(WORKOUTS,all);location.reload()}
function finish(w){w.completedAt=new Date().toISOString();w.status='completed';saveWorkout(w);const core=read(CORE,{checkins:{},activities:[]});core.activities=(core.activities||[]).filter(a=>a.workoutDate!==w.date);core.activities.push({id:'guided-'+w.date,date:w.date,workoutDate:w.date,type:'Entrenamiento',duration:'',distance:'',notes:w.title,exerciseLog:w.exercises.map(e=>({name:e.name,sets:e.sets,done:e.done})),savedAt:w.completedAt,completedAt:w.completedAt,status:'completed',source:'guided'});write(CORE,core);alert('Entrenamiento finalizado y guardado.');location.reload()}
function openWorkout(w){document.querySelectorAll('.v064-modal,.v063-modal').forEach(x=>x.remove());const m=document.createElement('div');m.className='v05-modal v064-modal';m.innerHTML=`<div class="v05-box"><div class="v05-head"><div><span class="tag">ENTRENAMIENTO EN CURSO</span><h2>${safe(w.title)}</h2></div><button class="v05-close" data-close>×</button></div><div class="v05-actions"><button class="btn alt" id="v064Chat">💬 PREGUNTAR / CAMBIAR</button><button class="btn alt" id="v064Save">GUARDAR Y SALIR</button></div><div id="v064Body"></div><button class="btn" id="v064Finish">✅ FINALIZAR ENTRENAMIENTO</button><button class="btn bad" id="v064Discard" style="margin-top:10px">🗑️ DESCARTAR ENTRENAMIENTO</button></div>`;document.body.appendChild(m);document.body.style.overflow='hidden';const body=m.querySelector('#v064Body');body.innerHTML=w.exercises.map((e,i)=>`<div class="v05-ex"><h3>${i+1}. ${safe(e.name)}</h3><p class="v05-sectionnote">${safe(e.planned?.reps||'')} · descanso ${safe(e.planned?.rest_seconds||'')} s<br>${safe(e.planned?.load_guidance||'')}<br>${safe(e.planned?.technique||'')}</p><div class="v05-setlabels"><span>Serie</span><span>Peso kg</span><span>Reps</span><span>Hecho</span></div>${(e.sets||[]).map((s,j)=>`<div class="v05-set"><b>${j+1}</b><input type="number" step=".5" inputmode="decimal" data-i="${i}" data-j="${j}" data-k="weight" value="${safe(s.weight)}"><input type="number" inputmode="numeric" data-i="${i}" data-j="${j}" data-k="reps" value="${safe(s.reps)}"><button type="button" class="v05-check ${s.done?'on':''}" data-check="${i}:${j}">${s.done?'✓':'○'}</button></div>`).join('')}</div>`).join('');m.querySelectorAll('[data-k]').forEach(inp=>inp.onchange=()=>{w.exercises[+inp.dataset.i].sets[+inp.dataset.j][inp.dataset.k]=inp.value;saveWorkout(w)});m.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.check.split(':').map(Number),s=w.exercises[i].sets[j];s.done=!s.done;w.exercises[i].done=w.exercises[i].sets.every(x=>x.done);b.classList.toggle('on',s.done);b.textContent=s.done?'✓':'○';saveWorkout(w)});const close=()=>{saveWorkout(w);closeModal(m)};m.querySelector('[data-close]').onclick=close;m.querySelector('#v064Save').onclick=close;m.querySelector('#v064Discard').onclick=discard;m.querySelector('#v064Finish').onclick=()=>finish(w);m.querySelector('#v064Chat').onclick=()=>openChat(w)}
let chatHistory=[];
function openChat(w=null){document.querySelectorAll('.v064-chat').forEach(x=>x.remove());const m=document.createElement('div');m.className='v05-modal v064-chat';m.innerHTML=`<div class="v05-box"><div class="v05-head"><div><span class="tag">ENTRENADOR</span><h2>Pregunta o cambia algo</h2></div><button class="v05-close" data-close>×</button></div><div class="card"><div id="v064ChatLog" class="v05-chatlog"></div><textarea id="v064ChatText" placeholder="Escribe tu pregunta…"></textarea><button class="btn" id="v064Send" style="margin-top:8px">ENVIAR</button></div></div>`;document.body.appendChild(m);document.body.style.overflow='hidden';const log=m.querySelector('#v064ChatLog');const render=()=>{log.innerHTML=chatHistory.map(x=>`<div class="v05-msg ${x.role==='me'?'v05-me':'v05-coach'}">${safe(x.text)}</div>`).join('');log.scrollTop=log.scrollHeight};render();let changed=false;m.querySelector('[data-close]').onclick=()=>{closeModal(m);if(changed)location.reload()};m.querySelector('#v064Send').onclick=async()=>{const input=m.querySelector('#v064ChatText'),text=input.value.trim(),btn=m.querySelector('#v064Send');if(!text)return;chatHistory.push({role:'me',text});render();input.value='';btn.disabled=true;btn.textContent='EL ENTRENADOR ESTÁ PENSANDO…';const core=read(CORE,{checkins:{},activities:[]}),plans=read(PLANS,{});try{const r=await fetch(COACH+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,checkin:core.checkins?.[iso()]||{},currentPlan:plans[iso()]||null,workoutProgress:w||store()[iso()]||null,recentHistory:(core.activities||[]).slice(-8)})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||`Error ${r.status}`);chatHistory.push({role:'coach',text:d.reply||'He revisado tu petición.'});if(d.updated_session){const p=plans[iso()]||{};p.session=d.updated_session;p.generatedAt=new Date().toISOString();plans[iso()]=p;write(PLANS,plans);const all=store();if(all[iso()]&&!all[iso()].completedAt)delete all[iso()];write(WORKOUTS,all);changed=true;chatHistory.push({role:'coach',text:'Sesión actualizada. Al cerrar el chat verás el nuevo entrenamiento.'})}render()}catch(err){chatHistory.push({role:'coach',text:'No pude responder: '+err.message});render()}finally{btn.disabled=false;btn.textContent='ENVIAR'}}}
function startNow(){const w=makeWorkout();if(!w){alert('No se pudo crear la sesión. Vuelve a generar el entrenamiento.');return}openWorkout(w)}
function handleRealButtons(e){const start=e.target.closest('#v05StartWorkout,#beginCoach');if(start){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();startNow();return}const chat=e.target.closest('#v05ChatBefore');if(chat){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openChat(store()[iso()]||null)}}
window.addEventListener('click',handleRealButtons,true);
function repairButtons(){const s=$('#v05StartWorkout');if(s)s.style.pointerEvents='auto';const c=$('#v05ChatBefore');if(c)c.style.pointerEvents='auto';const resume=$('#v062Resume');if(resume)resume.onclick=()=>{const w=store()[iso()];w?openWorkout(w):startNow()}}
const obs=new MutationObserver(repairButtons);obs.observe(document.body,{childList:true,subtree:true});repairButtons();
const ver=()=>{const d=$('#date');if(d)d.innerHTML=d.innerHTML.split('<br>')[0]+'<br>v0.6.4';const v=$('.version');if(v)v.textContent='Entrenador Personal · v0.6.4'};ver();setTimeout(ver,900);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=064').then(r=>r.update()).catch(()=>{}));
})();
