(() => {
'use strict';
const CHAT='https://entrenador-personal-coach.morrondin.workers.dev/chat';
const previousFetch=window.fetch.bind(window);
const safeSession=x=>x?.session?x.session:x||null;
const clone=x=>JSON.parse(JSON.stringify(x));
const isBike=n=>/\b(bici|bicicleta|spinning|ciclismo|cycling|cicloerg[oó]metro)\b/i.test(String(n||''));
const noBike=t=>/(\bno\s+(quiero|hago|hacer|metas?|pongas?)\b.*\b(bici|bicicleta)\b|\b(sin|quita|quitar|elimina|eliminar)\s+(la\s+)?(bici|bicicleta)\b|\bno\s+bici\b)/i.test(String(t||''));
const wantsBike=t=>/(\bmetemos?\s+(bici|bicicleta)\b|\bañad(e|imos?)\s+(bici|bicicleta)\b|\by\s+no\s+metemos?\s+(bici|bicicleta)\b|\bquiero\s+(bici|bicicleta)\b)/i.test(String(t||''));
function stripBike(session){const s=clone(session);if(!s)return s;if(Array.isArray(s.exercises))s.exercises=s.exercises.filter(e=>!isBike(e?.name));return s}
function addBike(session){const s=clone(session);if(!s)return s;s.exercises=Array.isArray(s.exercises)?s.exercises:[];if(!s.exercises.some(e=>isBike(e?.name)))s.exercises.unshift({name:'Bicicleta estática',sets:1,reps:'15–20 min',rest_seconds:0,load_guidance:'RPE 3–4/10, resistencia baja-moderada',technique:'Cadencia cómoda. Detener si aumenta claramente dolor, tirantez o hinchazón del Aquiles.'});const base=Number(s.duration_minutes||0);s.duration_minutes=Math.max(base,base+15);return s}
function fallback(body={}){const text=String(body.message||''),current=safeSession(body.currentPlan);if(noBike(text)){return {reply:'Perfecto. Quito la bici de la sesión de hoy.',updated_session:current?stripBike(current):null,local_fallback:true}}if(wantsBike(text)){const ach=String(body.checkin?.achilles||'').toLowerCase();if(/rojo|dolor/.test(ach))return {reply:'Hoy no la añadiría porque has marcado el Aquiles en rojo/dolor. Mejor mantengo la sesión sin bici.',local_fallback:true};return {reply:'Sí. Si tienes bici estática disponible hoy y el Aquiles sigue verde, encaja bien. La añado suave, 15–20 min, sin resistencia alta.',updated_session:current?addBike(current):null,local_fallback:true}}return {reply:'El entrenador online está tardando demasiado. Puedo aplicar cambios simples al plan desde el modo local; prueba con “quita bici”, “mete bici” o “cambia este ejercicio”.',local_fallback:true}}
window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:(input?.url||''),method=(init?.method||'GET').toUpperCase();if(method==='POST'&&url===CHAT){let body={};try{body=JSON.parse(init.body||'{}')}catch{}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await previousFetch(input,{...init,signal:controller.signal});if(r.ok)return r;if(r.status<500&&r.status!==429)return r;return new Response(JSON.stringify(fallback(body)),{status:200,headers:{'Content-Type':'application/json','X-Trainer-Chat-Fallback':'local'}})}catch(e){return new Response(JSON.stringify(fallback(body)),{status:200,headers:{'Content-Type':'application/json','X-Trainer-Chat-Fallback':'local'}})}finally{clearTimeout(timer)}}return previousFetch(input,init)};
const ver=()=>{const d=document.querySelector('#date');if(d)d.innerHTML=d.innerHTML.split('<br>')[0]+'<br>v0.7.0';const v=document.querySelector('.version');if(v)v.textContent='Entrenador Personal · v0.7.0'};ver();setTimeout(ver,900);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=070').then(r=>r.update()).catch(()=>{}));
})();
